version: '3.9'

services:
  api_contact_book:
    build: ./backend
    ports:
      - 8080:8080
    volumes:
      - ./backend/:/app:rw
    depends_on:
      contact_database:
        condition: service_healthy

  contact_database:
    image: postgres:14
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=contact_database
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d contact_database"]
      interval: 10s
      timeout: 15s
      retries: 5
      start_period: 30s
  
  frontend:
    build: ./frontend
    ports:
      - 3000:3000
    volumes:
      - ./frontend/:/app:rw
    depends_on:
      contact_database:
        condition: service_healthy
      contact_database:
        condition: service_healthy